In [2]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Discount (%),Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
0,TXN500001,CUST102534,01-01-2023,51,Male,Chennai,Online,Flipkart,Clothing,Kurta,...,64,0,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly
1,TXN500002,CUST101256,01-01-2023,27,Female,Mumbai,Offline,NaN,Clothing,Shirt,...,48,0,NaN,0,No,UPI,5,Not Returned,0,Fortnightly
2,TXN500003,CUST100490,01-01-2023,57,Male,Hyderabad,Online,Flipkart,Clothing,Jacket,...,22,0,Standard,7,Yes,UPI,3,Not Returned,0,Rarely
3,TXN500004,CUST100500,01-01-2023,22,Female,Pune,Online,Myntra,Clothing,Kurta,...,24,0,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly
4,TXN500005,CUST101399,01-01-2023,30,Male,Visakhapatnam,Online,Myntra,Accessories,Cap,...,30,99,Express,2,No,Debit Card,4,Not Returned,0,Weekly

In [4]:
df.tail()

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Discount (%),Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
9995,TXN509996,CUST102996,31-12-2024,30,Male,Bangalore,Online,Flipkart,Clothing,Trousers,...,9,199,Express,4,No,Debit Card,3,Not Returned,8,Fortnightly
9996,TXN509997,CUST100273,31-12-2024,58,Female,Kolkata,Online,Flipkart,Clothing,Saree,...,6,149,Express,4,No,UPI,5,Not Returned,1,Monthly
9997,TXN509998,CUST100566,31-12-2024,27,Female,Chennai,Online,Myntra,Clothing,Trousers,...,14,0,Standard,8,No,UPI,4,Not Returned,5,Weekly
9998,TXN509999,CUST102017,31-12-2024,48,Male,Bangalore,Online,Myntra,Footwear,Sandals,...,7,99,Standard,5,No,UPI,4,Not Returned,1,Monthly
9999,TXN510000,CUST100573,31-12-2024,20,Male,Pune,Online,Flipkart,Clothing,Hoodie,...,11,0,Standard,5,No,Debit Card,4,Not Returned,1,Monthly

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  object
 1   Customer ID             10000 non-null  object
 2   Purchase Date           10000 non-null  object
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  object
 5   Location                10000 non-null  object
 6   Online/Offline          10000 non-null  object
 7   Online Store            7751 non-null   object
 8   Category                10000 non-null  object
 9   Item Purchased          10000 non-null  object
 10  Brand                   10000 non-null  object
 11  Color                   10000 non-null  object
 12  Size                    8965 non-null   object
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Shipping Charge (₹)     10000 non-null  int64
 17  Delivery Speed          7751 non-null   object
 18  Delivery Time (Days)    10000 non-null  int64
 19  Subscription Status     10000 non-null  object
 20  Payment Method          10000 non-null  object
 21  Review Rating           10000 non-null  int64
 22  Return Status           10000 non-null  object
 23  Previous Purchases      10000 non-null  int64
 24  Frequency of Purchases  10000 non-null  object
dtypes: int64(8), object(17)
memory usage: 1.9+ MB

In [4]:
print("Rows:",df.shape[0])
print("columns:",df.shape[1])

Rows: 10000
columns: 25

In [5]:
df['Online Store']=df['Online Store'].fillna('In-store Purchase')

In [13]:
df['Size']=df['Size'].fillna('Free Size') 
df.iloc[30:41].head(10)

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases,Age group
30,TXN500031,CUST102593,03-01-2023,21,Female,Chandigarh,Offline,In-store Purchase,Footwear,Formal Shoes,...,0,N/A(Offline),0,No,UPI,4,Not Returned,0,Weekly,Young Adult
31,TXN500032,CUST100802,04-01-2023,39,Female,Kochi,Offline,In-store Purchase,Footwear,Sandals,...,0,N/A(Offline),0,Yes,UPI,4,Returned,0,Monthly,Middle-aged
32,TXN500033,CUST100379,04-01-2023,29,Male,Kolkata,Online,Amazon,Clothing,Shirt,...,79,Standard,8,No,Credit Card,4,Not Returned,0,Weekly,Adult
33,TXN500034,CUST100517,04-01-2023,20,Male,Patna,Online,Ajio,Accessories,Watch,...,0,Standard,6,Yes,UPI,3,Not Returned,0,Weekly,Young Adult
34,TXN500035,CUST102338,04-01-2023,19,Male,Lucknow,Online,Shein,Accessories,Sunglasses,...,0,Standard,6,Yes,UPI,3,Returned,0,Fortnightly,Young Adult
35,TXN500036,CUST100773,04-01-2023,48,Male,Nagpur,Online,Myntra,Clothing,Jacket,...,99,Standard,8,No,Cash on Delivery,3,Not Returned,0,Monthly,Middle-aged
36,TXN500037,CUST102876,04-01-2023,45,Female,Bangalore,Online,Myntra,Accessories,Backpack,...,0,Express,3,Yes,Credit Card,3,Not Returned,0,Rarely,Middle-aged
37,TXN500038,CUST100566,04-01-2023,27,Female,Chennai,Offline,In-store Purchase,Clothing,Dress,...,0,N/A(Offline),0,No,UPI,4,Not Returned,0,Weekly,Young Adult
38,TXN500039,CUST100093,04-01-2023,34,Female,Bangalore,Online,Myntra,Footwear,Sneakers,...,99,Standard,5,No,UPI,4,Not Returned,0,Weekly,Adult
39,TXN500040,CUST100010,04-01-2023,40,Male,Kolkata,Online,Amazon,Clothing,Jacket,...,79,Standard,5,No,Wallet,5,Not Returned,0,Fortnightly,Middle-aged

In [7]:
df['Delivery Speed']=df['Delivery Speed'].fillna('N/A(Offline)')

In [12]:
df.isnull().sum()

Transaction ID            0
Customer ID               0
Purchase Date             0
Age                       0
Gender                    0
Location                  0
Online/Offline            0
Online Store              0
Category                  0
Item Purchased            0
Brand                     0
Color                     0
Size                      0
Quantity                  0
Purchase Amount (₹)       0
Discount (%)              0
Shipping Charge (₹)       0
Delivery Speed            0
Delivery Time (Days)      0
Subscription Status       0
Payment Method            0
Review Rating             0
Return Status             0
Previous Purchases        0
Frequency of Purchases    0
Age group                 0
dtype: int64

In [11]:
labels=['Young Adult','Adult','Middle-aged','senior']
df['Age group']=pd.qcut(df['Age'],q=4,labels=labels)

In [17]:
df[['Age','Age group']].head(10)

   Age    Age group
0   51       senior
1   27  Young Adult
2   57       senior
3   22  Young Adult
4   30        Adult
5   57       senior
6   42  Middle-aged
7   47  Middle-aged
8   37        Adult
9   33        Adult

In [18]:
df.to_csv("cleaned_dataset.csv", index=False)